[build]
command = "npmrunbuild"
publish = "dist"
functions = "netlify/functions"

[build.environment]
SECRETS_SCAN_ENABLED = "false"

[functions]
external_node_modules = ["lightningcss", "express"]
node_bundle = true