[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[buid.environment]
  SECRETS_SCAN_ENABLED = "false"

[functions]
  external_node_modules = ["lightningcss", "express"]

[functions.node_bundle]
