[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["lightningcss", "express"]

[functions.node_bundle]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200
